language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - DEFAULT=1
    - PHPCS=0

matrix:
  fast_finish: true

before_script:
  - composer install --prefer-dist --no-interaction
  - sh -c "if [ '$PHPCS' = '1' ]; then composer require cakephp/cakephp-codesniffer:dev-master; fi"

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs --config-set installed_paths vendor/cakephp/cakephp-codesniffer; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=CakePHP --ignore=vendor --ignore=config/Migrations -v . ; fi"

notifications:
  email: false